mode: normal
normal_path: None

align_corner: False

nepoch: 80
batchsize: 24
num_workers: 4
lrate_decay_steps: 10000
lrate_decay_factor: 1.0

normal:
  depth_grad: True
  lambda_mse: 1.0
  lambda_ang: 1.0
  lr: 1e-3
  norm_layer: batch

num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10


