nepoch: 40
batchsize: 96
num_workers: 24
lr: 1e-4
lrate_decay_steps: 5000
lrate_decay_factor: 1.0
lambda_mse: 0.3
lambda_ang: 1.0

normal:
  norm_layer: group
  depth_type: midas
  norm_type: zero

num_view_all: 9
autocast: True
pinned: True
randomseed: 7633
i_img: 100
i_img_up: 1.3
i_save: 2000
i_print: 10




