nepoch: 30

batchsize: 16
num_workers: 6

lr: 1e-4
lrate_decay_steps: 5000
lrate_decay_factor: 0.5

norm_layer: group
depth_type: mvs

is_Light: False
SGNum: 6
env_height: 8
env_width: 16
env_rows: 30
env_cols: 40
lambda_mse: 0.3
lambda_ang: 1.0

num_view_all: 9
autocast: True
randomseed: 2245
i_img: 500
i_print: 10




