nepoch: 40
num_workers: 16
lr_feature: 1e-4
lr_mlp: 1e-4
lr_refine: 1e-4
lambda_albedo: 3.0
lambda_rough: 1.0
lambda_conf: 0.5
lrate_decay_steps: 10000
lrate_decay_factor: 1.0
depth_gt: True

normal:
  path: 20220517_stage1-1_group_1e-4_64
  depth_type: mvs
  norm_layer: group

DL:
  path: 05201732_stage1-2_batch_1e-4
  norm_layer: batch
  SGNum: 4
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40

BRDF:
  input_feature: rgb
#  input_feature: rgbdc
#  input_pbr_mlp: vector
  input_pbr_mlp: dot
  feature_dims: 24
  norm_layer: group
  refine_input: dc
#  refine_input: rgbdc


GL:
  env_height: 8
  env_width: 16
  env_rows: 120
  env_cols: 160

imWidth: 640
imHeight: 480
num_view_all: 9
num_view_min: 6
autocast: True
pinned: True
randomseed: 3127
i_img: 100
i_save: 3000
i_print: 10


