nepoch: 60
batchsize: 16
num_workers: 10
lr: 1e-4
lrate_decay_steps: 5000
lrate_decay_factor: 1.0
lambda_mse: 0.3
lambda_ang: 1.0

normal:
  norm_layer: group

num_view_all: 9
autocast: True
pinned: True
randomseed: 121
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10




