mode: normal

nepoch: 80
batchsize: 16
num_workers: 6
lrate_decay_steps: 10000
lrate_decay_factor: 0.9

normal:
  lambda_mse: 0.3
  lambda_ang: 1.0
  lr: 1e-4
  norm_layer: group

num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10


