mode: finetune

nepoch: 10
batchsize: 2
num_workers: 0
lrate_decay_steps: 10000
lrate_decay_factor: 1.0

stage1_path: 07191109_stage1

normal:
  norm_layer: group

DL:
  unified_decoder: False
  norm_layer: batch
  SGNum: 4
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40

BRDF:
  gt: False
  lambda_albedo: 3.0
  lambda_rough: 1.0

  context_feature:
    dim: 32
    norm_layer: group
    lr: 1e-4

  aggregation:
    pbr_hidden: 32
    input: dot
    pbr_feature_dim: 8
    norm_layer: layer
    head_dim: 16
    mlp_hidden: 16
    final_hidden: 32
    lr: 1e-4

  refine:
    lr: 1e-4
    norm_layer: group

SVL:
  vsg_dim: 128
  c_dim: 128
  GL:
    lr: 1e-4
  decoder:
    lr: 1e-4

  env_height: 8
  env_width: 16
  env_rows: 120
  env_cols: 160

imWidth: 320
imHeight: 240
num_view_all: 9
num_view_min: 6
autocast: True
pinned: True
randomseed: 3127
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10

