nepoch: 40
batchsize: 2
num_workers: 10
lrate_decay_steps: 10000
lrate_decay_factor: 1.0

normal:
  norm_layer: group

DL:
  norm_layer: batch
  SGNum: 3
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40

BRDF:
  lambda_albedo: 3.0
  lambda_rough: 1.0
  lambda_conf: 0.2

  feature:
    input: rgbdc
    dim: 16
    lr: 1e-4

  aggregation:
#    type: mlp
    pbr_hidden: 64
    input: dot
    pbr_feature_dim: 16

    type: transformer
    num_depth: 3
    num_head: 1
    head_dim: 16
    mlp_hidden: 16
    final_hidden: 64
    lr: 1e-4

  refine:
    use: True
    input: rgbdc
    lr: 1e-4
    norm_layer: group

  conf:
    use: False
    loss: linear

GL:
  env_height: 8
  env_width: 16
  env_rows: 120
  env_cols: 160

imWidth: 640
imHeight: 480
num_view_all: 9
num_view_min: 6
autocast: True
pinned: True
randomseed: 3127
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10

