nepoch: 60
batchsize: 2
num_workers: 10
lr_feature: 1e-4
lr_mlp: 1e-4
lr_refine: 1e-4
lambda_albedo: 3.0
lambda_rough: 1.0
lambda_conf: 0.2
confloss: linear
lrate_decay_steps: 10000
lrate_decay_factor: 1.0

normal:
  norm_layer: group

DL:
  norm_layer: batch
  SGNum: 3
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40

BRDF:
#  input_feature: rgb
  input_feature: rgbdc
  net_type: mlp
#  input_pbr_mlp: vector
  input_pbr_mlp: dot
  feature_dims: 24
  norm_layer: group
#  refine_input: dc
  refine_input: dc
  conf: False

GL:
  env_height: 8
  env_width: 16
  env_rows: 120
  env_cols: 160

imWidth: 640
imHeight: 480
num_view_all: 9
num_view_min: 6
autocast: True
pinned: True
randomseed: 3127
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10

