mode: DL
normal_path: 07251343_stage1

nepoch: 100
batchsize: 24
num_workers: 4
lrate_decay_steps: 10000
lrate_decay_factor: 0.9

normal:
  depth_grad: True
  lambda_mse: 1.0
  lambda_ang: 1.0
  norm_layer: batch

DL:
  lambda_vis_prior: 0.001
  lr: 1e-4
  scale_inv: True
  norm_layer: batch

  SGNum: 4
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40

num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10


