nepoch: 5

batchsize: 16
lr: 1e-4
lrate_decay_steps: 10000
lrate_decay_factor: 0.5

normalization: group
net_type: unet

loss: conf
lambda_conf: 0.2
#loss: gaussian
#lambda_gaussian: 0.1
lambda_L1: 1.0

num_view_all: 9
distributed: True
num_workers: 6
autocast: True
randomseed: 2245
i_img: 1000
i_print: 10


