mode: DL

nepoch: 80
batchsize: 16
num_workers: 6
lrate_decay_steps: 10000
lrate_decay_factor: 0.8

normal:
  lambda_mse: 1.0
  lambda_ang: 1.0
  lr: 1e-4
  norm_layer: group

DL:
  lambda_vis_prior: 0.001
  lr: 1e-3
  scale_inv: True
  unified_decoder: False
  norm_layer: batch

  SGNum: 4
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40

num_view_all: 9
autocast: True
pinned: True
randomseed: 2245
i_img: 100
i_img_up: 1.2
i_save: 4000
i_print: 10


