nepoch: 10
batchsize: 2
num_workers: 8
lrate_decay_steps: 10000
lrate_decay_factor: 1.0

normal:
  path: 06142149_stage1-1
  norm_layer: group

DL:
  path: 06221801_stage1-2
  unified_decoder: False
  norm_layer: batch
  SGNum: 4
  env_height: 8
  env_width: 16
  env_rows: 30
  env_cols: 40


BRDF:
  except_feature: True
  gt: True
  lambda_albedo: 3.0
  lambda_rough: 1.0
  lambda_conf: 0.2

  context_feature:
    input: rgbdc
    dim: 32
    norm_layer: group
    lr: 1e-4

  aggregation:
    pbr_collect: sum
    pbr_hidden: 32
    input: dot
    pbr_feature_dim: 8
    type: transformer
    norm_layer: layer
    head_dim: 16
    mlp_hidden: 16
    final_hidden: 32
    lr: 1e-4

  refine:
    context_concat: True
    use: True
    lr: 1e-4
    norm_layer: group

  conf:
    use: False
    loss: linear

GL:
  env_height: 8
  env_width: 16
  env_rows: 120
  env_cols: 160

imWidth: 640
imHeight: 480
num_view_all: 9
num_view_min: 6
autocast: True
pinned: True
randomseed: 3127
i_img: 100
i_img_up: 1.2
i_save: 3000
i_print: 10

